spectacular: spectacular.c performance.c read_seed.c get_random_number.c 
	gcc -o spectacular spectacular.c performance.c read_seed.c get_random_number.c -pthread -I. 
	
.PHONY: clean

clean:
	rm -f spectacular 
