spectacular: fedOops.c queue.c teamMember.c read_seed.c get_random_number.c 
	gcc -o fedOops fedOops.c queue.c teamMember.c read_seed.c get_random_number.c -lpthread -lrt -I. 

clean:
	rm -f fedOops


